---
deployment:
#  branch: static
  tasks:
    - export DEPLOYPATH=/home/ycvn0392/public_html
    - cd $DEPLOYPATH
    - /bin/cp -R /repositories/BURGER-PROD.
    - /usr/bin/composer install --no-dev --optimize-autoloader
    - /usr/bin/php $DEPLOYPATH/bin/console cache:clear --env=prod